# Generated by Django 5.1.1 on 2024-09-17 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_moodentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pemesan', models.CharField(max_length=100)),
                ('buku', models.CharField(choices=[('Fathul Qorib', 'Fathul Qorib'), ("I'anatut tholibin", "I'anatut tholibin"), ("Is'adur rofiq", "Is'adur rofiq"), ('Siroh nabawiyah', 'Siroh nabawiyah'), ('Shohih bukhori', 'Shohih bukhori'), ('Shohih muslim', 'Shohih muslim'), ('Idhohul mubham', 'Idhohul mubham')], max_length=100)),
                ('pcs', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
